=== Yashjani64/CS612-Concepts-and-Structures-in-Internet-Computing-Assignment-3.3/djmusicplaylist.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT music (playlist+)>
<!ELEMENT playlist (genrename, songname, artist, release-in, bpn)>
<!ELEMENT genrename (#PCDATA)>
<!ELEMENT songname (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT release-in (#PCDATA)>
<!ELEMENT bpn (#PCDATA)>
<!ATTLIST playlist id CDATA #REQUIRED>

=== Yashjani64/CS612-Concepts-and-Structures-in-Internet-Computing-Assignment-3.3/djmusicplaylist-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  music SYSTEM "djmusicplaylist.dtd">
<music>
  <playlist id="1">
	 <genrename>Hip Hop</genrename>
     <songname>Mind Playing Tricks on Me</songname>
	 <artist>Geto Boys </artist>
	 <release-in>1991</release-in>
     <bpn>120</bpn>
  </playlist>

   <playlist id="2">
	 <genrename>Romantic</genrename>
     <songname>Perfect</songname>
	 <artist>Ed Sheeran</artist>
	 <release-in>2017</release-in>
     <bpn>70</bpn>
  </playlist>

   <playlist id="3">
	 <genrename>Country</genrename>
     <songname>Fancy</songname>
	 <artist>Reba McEntire</artist>
	 <release-in>1990</release-in>
     <bpn>100</bpn>
  </playlist>
</music>
